# This file provides per host configuration
# NOTE: currently any variables set in here will
#  a) not be read on vagrant provisioning (it uses a separate inventory file)
#  b) be overriden by config-global.yml

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    root_user: root
  hosts:
    vagrant:
      # requires first running `vagrant ssh-config > vagrant-ssh`
      cloud_platform: virtualbox
      ansible_host: default
      ansible_ssh_common_args: "-F vagrant-ssh"
      ansible_user: vagrant
    aws:
      cloud_platform: aws
      ansible_host: 34.250.68.129 # change this
      ansible_ssh_common_args: -i ./keys/quantum-mobile.pem -o StrictHostKeyChecking=no
      ansible_user: ubuntu
    hwcloud:
      cloud_platform: hwcloud
      ansible_host: 34.250.68.129 # change this
      ansible_ssh_common_args: -i ./keys/quantum-mobile.pem -o StrictHostKeyChecking=no
      ansible_user: root
    openstack:
      cloud_platform: openstack
      ansible_host: 34.250.68.129 # change this
      ansible_ssh_common_args: -i ./keys/quantum-mobile.pem -o StrictHostKeyChecking=no
      ansible_user: ubuntu
    gcp:
      cloud_platform: gcp
      ansible_host: 34.250.68.129 # change this
      ansible_ssh_common_args: -i ./keys/quantum-mobile.pem -o StrictHostKeyChecking=no
      ansible_user: max
