- name: Install ansible prerequisites

  hosts: "{{ build_hosts | default('vagrant-ssh') }}"
  gather_facts: false

  pre_tasks:

  - name: test configuration
    debug:
      msg: RUNNING PLAYBOOK FOR '{{ vm_name }}' VERSION '{{ vm_version }}'
    tags: [init]
  - name: testing ansible environment
    debug:
      msg: Connecting to host '{{ inventory_hostname }}' as user '{{ ansible_user }}'
    tags: [init]
  - name: Make local dist folder
    local_action:
      module: file
      state: directory
      path: "{{ local_dist_folder }}/"
    when: release_notes_locally is defined and release_notes_locally
    tags: [init]

- name: set up the VM (abinit only)
  hosts: "{{ build_hosts | default('vagrant-ssh') }}"

  vars:
    libxc_version: "4.3.4"
    libxc_prefix: "/usr/local/libxc-{{ libxc_version }}"

  roles:

  - name: add user {{ vm_user }} with key
    role: marvel-nccr.add_user
    tags: [add_user]
    vars:
      add_user_name: "{{ vm_user }}"
      add_user_password: "{{ vm_password }}"
      add_user_groups:
      - "{{ vm_user }}"
      - sudo
      add_user_passwordless_sudo: true

  - role: marvel-nccr.simulationbase
    tags: [simulationbase]
    vars:
      simulationbase_vm_user: "{{ vm_user }}"
      simulationbase_hostname: "{{ vm_hostname }}"
      simulationbase_codes_folder: "{{ vm_codes_folder }}"
      simulationbase_tmz: Europe/Zurich

  - role: marvel-nccr.ubuntu_desktop
    tags: [ubuntu_desktop]
    vars:
      ubuntu_desktop_browser: "{{ vm_browser }}"
      ubuntu_desktop_vm_user: "{{ vm_user }}"
    when: not vm_headless

  - role: marvel-nccr.quantum_mobile_customizations
    tags: [qm_customizations]
    vars:
      qm_customizations_browser: "{{ vm_browser }}"
      qm_customizations_vm_user: "{{ vm_user }}"
      qm_customizations_vm_password: "{{ vm_password }}"
      qm_customizations_vm_name: "{{ vm_name }}"
      qm_customizations_vm_version: "{{ vm_version }}"
      qm_customizations_vm_author: "{{ vm_author }}"
      qm_customizations_headless: "{{ vm_headless }}"
      qm_customizations_examples_folder: "{{ vm_examples_folder }}"
      qm_customizations_data_folder: "{{ vm_data_folder }}"
      qm_customizations_readme_file: "{{ vm_readme_file }}"
      qm_customizations_homepage: "https://quantum-mobile.readthedocs.io"
      qm_customizations_urls:
        Abinit: https://www.abinit.org

  - role: marvel-nccr.editors
    tags: [editors]
    vars:
      editors_vm_user: "{{ vm_user }}"

  - role: marvel-nccr.slurm
    tags: [slurm]

  - role: marvel-nccr.libxc  # this is used by abinit and siesta
    tags: [abinit, siesta]
    vars:
      libxc_build_cpus: "{{ vm_cpus }}"

  - role: marvel-nccr.abinit
    tags: [abinit]
    vars:
      abinit_build_cpus: "{{ vm_cpus }}"
      abinit_libxc_path: "{{ libxc_prefix }}"

  - role: geerlingguy.nodejs  # this is used by jupyterlab and aiidalab
    tags: [aiida, nodejs]
    become: true
    become_user: "{{ root_user }}"
    vars:
      nodejs_version: 12.x
      nodejs_install_npm_user: "{{ root_user }}"

  - role: marvel-nccr.aiida
    tags: [aiida]
    become: true
    become_user: "{{ vm_user }}"
    vars:
      aiida_source_folder: "{{ vm_codes_folder }}"
      aiida_data_folder: "{{ vm_data_folder }}/aiida"
      aiida_computer_cpus: "{{ vm_cpus }}"
      aiida_computer_scheduler: "{{ vm_scheduler }}"
      aiida_examples_folder: "{{ vm_examples_folder }}"
      aiida_venv: "{{ aiida_venv_base }}/aiida"
      aiida_jupyter_venv: "{{ aiida_venv_base }}/jupyter"
      aiida_venv_constraints: "{{ vm_data_folder }}/aiida/constraints.txt"
      aiida_plugins:
        aiida-abinit:
          version: "0.2.0a1"
          code_prefix: abinit
          codes_var: "abinit_executables"

  - name: aiidalab
    role: marvel-nccr.aiidalab
    become: true
    become_user: "{{ vm_user }}"
    tags: [aiidalab]
    vars:
      aiidalab_aiida_venv: "{{ aiida_venv_base }}/aiida"
      aiidalab_aiida_jupyter_venv: "{{ aiida_venv_base }}/jupyter"
      aiidalab_aiida_venv_constraints: "{{ vm_data_folder }}/aiida/constraints.txt"

  post_tasks:

  - name: Check package version integrity in virtualenv
    command: "{{ aiida_venv }}/bin/pip check --no-color"
    become: true
    become_user: "{{ vm_user }}"
    changed_when: false
    tags: [aiida, aiidalab, pipcheck]
