name: CD

on:
  push:
    branches: [master]
    tags:
    - '*'
  pull_request:

jobs:

  build:

    # Vagrant builds require Mac OSX machines,
    # see: https://github.com/actions/virtual-environments/issues/183
    runs-on: macos-latest

    env:
      VAGRANT_NO_GUI: true
      VAGRANT_ON_GH: true

    steps:

    - uses: actions/checkout@v2

    - name: set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: install tox
      run: pip install tox

    - name: Build VM
      run: tox -e py38-build
      continue-on-error: true
      id: build_1

    # improve resilience, if ansible fails, for example due to a download timeout
    # ansible is idempotent, so in principle we can retry as many times as needed
    - name: Build VM (retry)
      if: failure() && steps.build_1.outcome == 'failure'
      run: tox -e py38-continue

    - name: Archive build log
      uses: actions/upload-artifact@v2
      with:
        name: build-log
        path: ansible.log
      continue-on-error: true

    - name: Clean build files on VM
      # only roles that include "when: clean is defined and clean"
      # TODO wannier90 has a clean task, but it appears to running against the wrong python executable
      # since it can't find the configparser module, pip installed in earlier task
      run: tox -e py38-continue -- --tags quantum_espresso,qm_customizations,simulationbase,ubuntu_desktop --extra-vars "clean=true"

    - name: Archive clean log
      uses: actions/upload-artifact@v2
      with:
        name: clean-log
        path: ansible.log
      continue-on-error: true

    - name: Package VM
      run: tox -e py38-package -- --skip-tags validate

    - name: Archive package log
      uses: actions/upload-artifact@v2
      with:
        name: package-log
        path: ansible.log
      continue-on-error: true

    # Note encountered: https://github.com/actions/upload-artifact/issues/84
    - name: Archive distribution
      uses: actions/upload-artifact@v2
      with:
        name: distribution
        path: dist/
