name: CI

on:
  push:
    branches: [master, develop]
    tags:
    - '*'
  pull_request:

jobs:

  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: pre-commit/action@v2.0.0

  build-init:
    # this job initialises the vagrant box
    # then just runs some initial ansible tasks
    # for the full build, see build.yml
    runs-on: macos-latest
    env:
      VAGRANT_NO_GUI: true
      VAGRANT_ON_GH: true
    steps:
    - uses: actions/checkout@v2
    - name: set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install tox
      run: pip install tox
    - name: Build Vagrant Box
      run: ANSIBLE_ARGS="--tags init" tox -e vagrant
    - name: Archive ansible log
      uses: actions/upload-artifact@v2
      with:
        name: ansible-log
        path: ansible.log

  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: install tox
      run: pip install tox
    - name: run build
      run: tox -e docs-clean
